/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import email from "@strapi/email/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import todo from "../../src/plugins/todo/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    email: email,
    "users-permissions": usersPermissions,
    todo: todo,
  },
});
