/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
<<<<<<< HEAD
=======
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
>>>>>>> 8fd964a075112ba665c636ac4ef629f0e24599b4
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
<<<<<<< HEAD
=======
    "users-permissions": usersPermissions,
>>>>>>> 8fd964a075112ba665c636ac4ef629f0e24599b4
    i18n: i18N,
    seo: seo,
  },
});
